# Generated by Django 4.0.4 on 2022-04-13 15:30

from django.db import migrations, models
import django.db.models.deletion
import places.utils


LOCATIONS = {
    "Экскурсионный проект «Крыши24.рф»": "Хотите увидеть Москву с высоты и разделить яркие впечатления с друзьями? В этом поможет проект «Крыши24.рф». Вы можете выбрать крышу из множества интересных вариантов и провести там свидание, вечеринку, творческое занятие, фотосессию или что-то ещё.",
    "Экскурсионная компания «Легенды Москвы»": "Неважно, живёте ли вы в Москве всю жизнь или впервые оказались в столице, составить ёмкий, познавательный и впечатляющий маршрут по городу — творческая и непростая задача. И её с удовольствием берёт на себя экскурсионная компания «Легенды Москвы»!"
}


def create_location(apps, schema):
    Location = apps.get_model('places', 'Location')
    Location.objects.bulk_create(
        [Location(title=title, description_short=dis)
         for title, dis in LOCATIONS.items()]
    )

def delete_location(apps, schema):
    Location = apps.get_model('places', 'Location')
    Location.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description_short', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to=places.utils.file_path, verbose_name='Файл')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.location')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langitude', models.CharField(blank=True, max_length=255, null=True)),
                ('lotitude', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.location')),
            ],
        ),
        migrations.RunPython(
            create_location,
            reverse_code=delete_location
        )
    ]
