# Generated by Django 4.0.4 on 2022-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_coordinates_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
    ]
