# Generated by Django 4.0.4 on 2022-04-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_location_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinates',
            options={'verbose_name': 'Координаты локаций', 'verbose_name_plural': 'Координаты локаций'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локаций'},
        ),
        migrations.AlterModelOptions(
            name='locationphoto',
            options={'verbose_name': 'Фото локаций', 'verbose_name_plural': 'Фото локаций'},
        ),
    ]
