# Generated by Django 4.0.4 on 2022-04-20 10:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_coordinates_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
